version: 0.2

env:
  parameter-store:
    ACCESS_TOKEN: '/service/mac-github-token'

phases:
  install:
    runtime-versions:
      nodejs: 20
      # commands:
      #   # Install all dependencies (including dependencies for running tests)
      #   - echo "GITHUB_ACCESS_TOKEN - $ACCESS_TOKEN"
      #   - echo "PASSING ENV - $test-passing-env"
      #   - npm install
      steps:
        - id: fetch-latest-release
          uses: thebritican/fetch-latest-release@v1
          with:
            github_token: $ACCESS_TOKEN
  pre_build:
    commands:
      # this is typescript so we need to compile it to JS first
      - npm run compile
  # build:
  #   commands:
  #     # Use AWS SAM to package the application by using AWS CloudFormation
  #     - aws cloudformation package --template template.yml --s3-bucket traced-code-deploy --s3-prefix test-deploy --output-template template-export.yml
  #     # Deploying AWS
  #     - aws cloudformation deploy --template template-export.yml --s3-bucket traced-code-deploy --s3-prefix test-deploy --stack-name sam-gradual-deploy --capabilities CAPABILITY_IAM
  # post_build:
  #   on-failure: ABORT
  #   steps:
  # - id: fetch-latest-release
  #   uses: thebritican/fetch-latest-release@v1
  #   with:
  #     github_token: $ACCESS_TOKEN
  # - name: 'Trigger E2E Test Workflow'
  #   uses: convictional/trigger-workflow-and-wait@v1.6.1
  #   with:
  #     owner: TracedLtd
  #     repo: Control-E2E-Tests
  #     github_token: $ACCESS_TOKEN
  #     github_user: MacAndersonUche
  #     workflow_file_name: e2e-tests-pipeline.yml
  #     wait_interval: 30
  #     propagate_failure: true
  #     trigger_workflow: true
  #     wait_workflow: true
artifacts:
  type: zip
  files:
    - template-export.yml
