version: 0.2

env:
  parameter-store:
    GITHUB_ACCESS_TOKEN: '/service/mac-github-token'

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install
  pre_build:
    commands:
      # this is typescript so we need to compile it to JS first
      - npm run compile
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket traced-code-deploy --s3-prefix test-deploy --output-template template-export.yml
  post_build:
    on-failure: ABORT
    commands:
      # Deploy the new stack replacing all the code etc
      # - aws cloudformation deploy --template template-export.yml --s3-bucket traced-code-deploy --s3-prefix test-deploy --stack-name sam-gradual-deploy --capabilities CAPABILITY_IAM
      # - npm run test
    steps:
      - id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v1
        with:
          github_token: $GITHUB_ACCESS_TOKEN
      ## IF Test passes create tag??
artifacts:
  type: zip
  files:
    - template-export.yml
