AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-gradual-deploy

Globals:
  Function:
    MemorySize: 1048
    Timeout: 60
    Runtime: nodejs20.x
    Tracing: Active

Resources:
  CodebuildEventRuleSQS:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 120
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CodebuildEventRuleDLQ.Arn
        maxReceiveCount: 2

  CodebuildEventRuleDLQ:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 120

  TriggerRebuild:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: trigger-rebuild
      Handler: dist/handle-redeploy/index.handler
      Description: Makes sure the api key used is valid
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: arn:aws:ssm:eu-west-2:725638684424:*
      Environment:
        Variables:
          GITHUB_ACCESS_TOKEN: '{{resolve:ssm:/service/mac-github-token:1}}'
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt CodebuildEventRuleSQS.Arn
            BatchSize: 1

  # Allow EventBridge to invoke SQS
  EventBridgeToToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt CodebuildEventRuleSQS.Arn
      Queues:
        - Ref: CodebuildEventRuleSQS

  CodebuildEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: EventRule for Codebuild
      Name: codebuild-rule
      EventPattern:
        source:
          - aws.codebuild
        detail-type:
          - CodeBuild Build Phase Change
        detail:
          completed-phase-status:
            - FAILED
          project-name:
            - sam-gradual-deploy
          completed-phase:
            - POST_BUILD
      State: ENABLED
      Targets:
        - Arn: !GetAtt CodebuildEventRuleSQS.Arn
          Id: 'SQSqueue'
