AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-gradual-deploy

Globals:
  Function:
    MemorySize: 1048
    Timeout: 60
    Runtime: nodejs20.x
    Tracing: Active

Resources:
  FailureSQS:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 120

  # Define the SNS topic
  CodebuildFailureTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: sqs
          Endpoint: !GetAtt FailureSQS.Arn

  # Policy allows SNS to publish to this SQS queue
  SnsToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Allow SNS publish to SQS'
            Effect: Allow
            Principal:
              Service: 'sns.amazonaws.com'
            Resource: !GetAtt FailureSQS.Arn
            Action: SQS:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref CodebuildFailureTopic
      Queues:
        - Ref: FailureSQS

  TriggerRebuild:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: trigger-rebuild
      Handler: dist/handlers/handle-redeploy/index.handler
      Description: Makes sure the api key used is valid
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: arn:aws:ssm:eu-west-2:725638684424:*
      Environment:
        Variables:
          GITHUB_ACCESS_TOKEN: '{{resolve:ssm:/service/mac-github-token:1}}'
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FailureSQS.Arn
            BatchSize: 1

  # MyNewEventsRule:
  #   Type: 'AWS::Events::Rule'
  #   Properties:
  #     Description: Test Events Rule
  #     Name: mynewabc
  #     EventPattern:
  #       source:
  #         - aws.ec2
  #     State: ENABLED
  #     Targets:
  #       - Arn: 'arn:aws:sqs:us-west-2:081035103721:demoSQS'
  #         Id: Id1234
  #         RetryPolicy:
  #           MaximumRetryAttempts: 4
  #           MaximumEventAgeInSeconds: 400
  #         DeadLetterConfig:
  #           Arn: 'arn:aws:sqs:us-west-2:081035103721:demoDLQ'
