AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-gradual-deploy

Globals:
  Function:
    MemorySize: 1048
    Timeout: 120
    Runtime: nodejs20.x
    Tracing: Active
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
        DEVICES_TABLE: devices
        API_KEYS_TABLE: api_keys
        CUSTOMERS_TABLE: customers

Resources:
  ExperimentApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,OPTIONS,PUT,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
        AllowOrigin: "'*'"

  # Define the SNS topic
  CodebuildFailureTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt RevertAndMergeMRAndTriggerRebuild.Arn

  # Provide permission for SNS to invoke the Lambda function
  CodebuildFailurePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref RevertAndMergeMRAndTriggerRebuild
      Principal: sns.amazonaws.com

  ExperimentGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'sam-deploy-lambda1'
      Handler: dist/handlers/index.handler
      Description: Makes sure the api key used is valid
      Events:
        TestGetDevice:
          Type: Api
          Properties:
            Path: /v1/test
            Method: GET
            RestApiId: !Ref ExperimentApi

  RevertAndMergeMRAndTriggerRebuild:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'revert-and-trigger-rebuild'
      Handler: dist/handlers/revert/index.handler
      Description: Makes sure the api key used is valid
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref CodebuildFailureTopic

Outputs:
  ApiDefaultEndpoint:
    Description: 'API Gateway default URL'
    Value: !Sub 'https://${ExperimentApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
