name: Deploy to Traced

on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build NodeJs Application
        run: npm run compile

      - name: Package Application
        run: |
          aws cloudformation package --template template.yml --s3-bucket traced-code-deploy --s3-prefix test-deploy --output-template template-export.yml

      - name: Deploy SAM Application
        run: |
          aws cloudformation deploy --template template-export.yml --s3-bucket traced-code-deploy --s3-prefix test-deploy --stack-name sam-gradual-deploy --capabilities CAPABILITY_IAM
