name: Deploy to Traced

on:
  push:
    branches:
      - mainx
jobs:
  build-deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build NodeJs Application
        run: npm run build

      - name: Build SAM Application
        run: |
          sam build

      - name: Deploy SAM Application
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name sam-gradual-deploy --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1k4cmkfqtipsy \
            --capabilities CAPABILITY_IAM  --region ${{ secrets.AWS_REGION }}
