name: Repo A Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trigger-repo-b-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 19
      - name: Process private key
        id: process-private-key
        run: |
          PROCESSED_PRIVATE_KEY=$(echo "${{ secrets.PRIVATE_KEY }}" | sed 's/\\n/\n/g')
          echo "PROCESSED_PRIVATE_KEY=$PROCESSED_PRIVATE_KEY" >> $GITHUB_ENV
      - uses: cybozu/octoken-action@v1
        id: app-token
        with:
          github_app_id: ${{ vars.APP_ID }}
          github_app_private_key: ${{ secrets.PRIVATE_KEY }}
    #   - name: 'Trigger E2E Test'
    #     uses: convictional/trigger-workflow-and-wait@v1.6.1
    #     with:
    #       owner: TracedLtd
    #       repo: Control-E2E-Tests
    #       github_token: ${{ secrets.GH_ACCESS_TOKEN }}
    #       github_user: MacAndersonUche
    #       workflow_file_name: e2e-tests-pipeline.yml
    #       wait_interval: 30
    #       propagate_failure: true
    #       trigger_workflow: true
    #       wait_workflow: true
