name: Using Github APP Workflow
on:
  push:
    branches:
      - master

jobs:
  testing-using-app:
    runs-on: ubuntu-18.04
    steps:
      - name: Process private key
        id: process-private-key
        run: |
          PROCESSED_PRIVATE_KEY=$(echo "${{ secrets.PRIVATE_KEY }}" | sed 's/\\n/\n/g')
          echo "PROCESSED_PRIVATE_KEY=$PROCESSED_PRIVATE_KEY" >> $GITHUB_ENV
      - uses: cybozu/octoken-action@v1
        id: app-token
        with:
          github_app_id: ${{ vars.APP_ID }}
          github_app_private_key: ${{  secrets.PRIVATE_KEY }}
