name: Repo A Workflow
on: [push]
jobs:
  trigger-repo-b-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2
        with:
          repository: TracedLtd/control-e2e-tests
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: 'Trigger B'
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: TracedLtd
          repo: Control-E2E-Tests
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          github_user: MacAndersonUche
          workflow_file_name: e2e-tests-pipeline.yml
          wait_interval: 30
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
    #   - name: Dispatch an action and get the run ID
    #     uses: codex-/return-dispatch@v1
    #     id: return_dispatch
    #     with:
    #       ref: 'main'
    #       token: ${{ secrets.GH_ACCESS_TOKEN }}
    #       repo: Control-E2E-Tests
    #       owner: TracedLtd
    #       workflow: e2e-tests-pipeline.yml
    #   - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
    #     uses: Codex-/await-remote-run@v1.0.0
    #     with:
    #       token: ${{ secrets.GH_ACCESS_TOKEN }}
    #       repo: Control-E2E-Tests
    #       owner: TracedLtd
    #       run_id: ${{ steps.return_dispatch.outputs.run_id }}
    #       run_timeout_seconds: 300 # Optional
    #       poll_interval_ms: 5000 # Optional

    #   - name: Trigger Repo B Workflow
    #     uses: actions/github-script@v6
    #     with:
    #       script: |
    #         await github.rest.actions.createWorkflowDispatch({
    #           owner: 'TracedLtd',
    #           repo: 'Control-E2E-Tests',
    #           workflow_id: 'e2e-tests-pipeline.yml',
    #           ref: 'main',
    #         });
    #       github-token: ${{ secrets.GH_ACCESS_TOKEN }}

    #   - name: Wait for Repo B Workflow to complete
    #     uses: lewagon/wait-on-check-action@v1.3.1
    #     with:
    #       ref: 'master'
    #       #   check-name: 'e2e-tests-pipeline'
    #       running-workflow-name: 'Run E2E Tests'
    #       repo-token: ${{ secrets.GH_ACCESS_TOKEN }}
    #       wait-interval: 60 # Poll every 60 seconds

    #   - name: Check Repo B Workflow Status
    #     uses: actions/github-script@v6
    #     with:
    #       script: |
    #         const run = await github.rest.actions.listWorkflowRuns({
    #           owner: 'TracedLtd',
    #           repo: 'Control-E2E-Tests',
    #           workflow_id: 'e2e-tests-pipeline.yml',
    #           per_page: 1,
    #         });
    #         if (run.data.status !== "completed" || run.data.conclusion !== "success") {
    #           throw new Error("Repo B workflow failed");
    #         }
    #       github-token: ${{ secrets.GH_ACCESS_TOKEN }}
