name: Repo A Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  process-private-key:
    runs-on: ubuntu-latest
    outputs:
      processed-private-key: ${{ steps.process.outputs.processed-private-key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Process private key
        id: process
        run: |
          PROCESSED_PRIVATE_KEY=$(echo "${{ secrets.PRIVATE_KEY }}" | sed 's/\\n/\n/g')
          echo "PROCESSED_PRIVATE_KEY=$PROCESSED_PRIVATE_KEY" >> $GITHUB_ENV
          echo "::set-output name=processed-private-key::$PROCESSED_PRIVATE_KEY"

  trigger-repo-b-workflow:
    needs: process-private-key
    runs-on: ubuntu-latest
    steps:
      - name: Debug private key
        run: 'echo Private Key: ${{ secrets.PRIVATE_KEY }}'
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ needs.process-private-key.outputs.processed-private-key }}
          owner: MacAndersonUche
      - name: 'Trigger E2E Test'
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: TracedLtd
          repo: Control-E2E-Tests
          github_token: ${{ steps.app-token.outputs.token }}
          github_user: MacAndersonUche
          workflow_file_name: e2e-tests-pipeline.yml
          wait_interval: 30
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
