name: Repo A Workflow
on: [push]
jobs:
  trigger-repo-b-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2
        with:
          repository: TracedLtd/control-e2e-tests
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Trigger Repo B Workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'TracedLtd',
              repo: 'Control-E2E-Tests',
              workflow_id: 'e2e-tests-pipeline.yml',
              ref: 'main',
            });
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Wait for Repo B Workflow to complete
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: 'main'
          check-name: 'e2e-tests-pipeline'
          repo-token: ${{ secrets.GH_ACCESS_TOKEN }}
          wait-interval: 60 # Poll every 60 seconds

      - name: Check Repo B Workflow Status
        uses: actions/github-script@v6
        with:
          script: |
            const run = await github.rest.actions.listWorkflowRuns({
              owner: 'TracedLtd',
              repo: 'Control-E2E-Tests',
              workflow_id: 'e2e-tests-pipeline.yml',
              per_page: 1,
            });
            if (run.data.status !== "completed" || run.data.conclusion !== "success") {
              throw new Error("Repo B workflow failed");
            }
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
