name: Repo A Workflow
on: [push]
jobs:
  trigger-repo-b-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2
        with:
          repository: TracedLtd/control-e2e-tests
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Trigger Repo B Workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'TracedLtd',
              repo: 'Control-E2E-Tests',
              workflow_id: 'e2e-tests-pipeline.yml',
              ref: 'main',
            });
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Check Repo B Workflow Status
        uses: actions/github-script@v6
        with:
          script: |
            const run = github.rest.actions.listWorkflowRuns({
              owner: "TracedLtd",
              repo: "Control-E2E-Tests",
              workflow_id: "e2e-tests-pipeline.yml",
              per_page: 1,
            });
            if (run.data.status !== "completed" || run.data.conclusion !== "success") {
              throw new Error("Repo B workflow failed");
            }
